emplManagement/urls.py
from django.contrib import admin
from django.urls import include, path
from emplManagement import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employees.urls')),
]

employees/urls.py
# employees/urls.py
from django.urls import path
from employees.views import *
from django.conf.urls.static import static
app_name ="employeesApp"

urlpatterns = [
path('', employeeList.as_view(), name='employee_list'),
path('add-employee', employeeAdd.as_view(), name='employee_add'),
path('edit-employee', employeeEdit.as_view(), name='employee_edit'),
]

employees/models.py
from django.db import models

# Create your models here.

class Employee(models.Model):
    DEPARTMENT = (
        (1, 'HR'),
        (2, 'DEVELOPMENT'),
        (3, 'BUSSINESS'),
        (4, 'TESTING'),
    )
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.CharField(max_length=254, null=True, blank=True)
    department = models.PositiveSmallIntegerField(choices=DEPARTMENT, default=1, null=True, blank=True)
    salary = models.DecimalField(max_digits=10, decimal_places=2)
    is_deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(null=True, blank=True,auto_now_add=True)
    updated_at = models.DateTimeField(null=True, blank=True,auto_now=True)

    class Meta:
        db_table = 'employees'

employees/views.py
from pyexpat.errors import messages
from urllib import request
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import View

from employees.models import Employee
from django.template.loader import render_to_string

# Create your views here.
class employeeList(View):
    def get(self, request):
        context={}
        print("sdcjsbhdjbsdjb")
        template_name = 'employee-list.html'
        employees = Employee.objects.filter(is_deleted=False).all()
        empl=[]
        for em in employees:
            array={'first_name':em.first_name,'last_name':em.last_name,'email':em.email,'department':em.get_department_display(),'salary':em.salary}
            empl.append(array)
        context['employees']=empl
        return render(request, template_name, context)
class employeeAdd(View):
    def get(self, request):
        context={}
        template_name = 'add-employee.html'
        employees = Employee.objects.all()
        context['employees']=employees
        return render(request, template_name, context)
    def post(self, request):
        try:
            if request.method == 'POST':
                fname = request.POST['name']
                lname = request.POST['lname']
                email = request.POST['email']
                depertment = request.POST['depertment']
                salary = request.POST['salary']
                empl = Employee(first_name=fname, last_name=lname,email=email, department=depertment, salary=salary)
                empl.save()
                print(fname,"----name")
                print(depertment,"----depertment")
                print(salary,"----salary")
                return redirect(reverse('employeesApp:employee_list'))
        except Exception as e:
            messages.add_message(request, messages.WARNING, f'Failed to update profile')
            # return HttpResponseRedirect(redirect_to='/profile')

class employeeEdit(View):
    def get(self, request):
        context={}
        template_name = 'add-list.html'
        employees = Employee.objects.all()
        context['employees']=employees
        return render(request, template_name, context)

templates/add-employee.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
  background-color: black;
}

* {
  box-sizing: border-box;
}

/* Add padding to containers */
.container {
  padding: 16px;
  background-color: white;
}

/* Full-width input fields */
input[type=text], input[type=password] {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

/* Overwrite default styles of hr */
hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}

/* Set a style for the submit button */
.registerbtn {
  background-color: #04AA6D;
  color: white;
  padding: 16px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

.registerbtn:hover {
  opacity: 1;
}

/* Add a blue text color to links */
a {
  color: dodgerblue;
}

/* Set a grey background color and center the text of the "sign in" section */
.signin {
  background-color: #f1f1f1;
  text-align: center;
}
</style>
</head>
<body>

<form id = "emplForm" method = "post" enctype="multipart/form-data">
    {% csrf_token %}
  <div class="container">
    <h1>Add Employee</h1>
    <p>Please fill in this form to add an employee.</p>
    <hr>
    <label for="name"><b>First Name</b></label>
    <input type="text" placeholder="Enter First Name" name="name" id="name" required>

    <label for="lname"><b>Last Name</b></label>
    <input type="text" placeholder="Enter Last Name" name="lname" id="lname" required>

    <label for="email"><b>Email</b></label>
    <input type="text" placeholder="Enter Email" name="email" id="email" required>

    <label for="Depertment"><b>Department</b></label>
    <br>
    <br>
    <select name="depertment" id="Depertment">
        <option value="1">HR</option>
        <option value="2">DEVELOPMENT</option>
        <option value="3">BUSSINESS</option>
        <option value="4">TESTING</option>
      </select>
    <br>
    <br>
    <br>
    <label for="Salary"><b>Salary</b></label>
    <input type="text" placeholder="Enter Salary" name="salary" id="Salary" required>
    <hr>
    
    <button type="submit" class="registerbtn">Add Employee</button>
  </div>
  
  
</form>

</body>
</html>

templates/employee-list.html
<!-- employees/templates/employees/employee_list.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Employee List</title>
</head>
<body>
    <h1>Employee List</h1><a href="{% url 'employeesApp:employee_add' %}" class="purple-btn">Add Employee</a>
    <ul>
        {% for employee in employees %}
        <li>{{ employee.first_name }} {{ employee.last_name }}({{ employee.email }}) - {{ employee.department }} (Salary: {{ employee.salary }})</li>
        {% endfor %}
    </ul>
</body>
</html>